class AddAlToAutointel < ActiveRecord::Migration
  def change
      add_column :autointel_rates, :AL, :float
	add_column :autointel_rates, :AK, :float
	add_column :autointel_rates, :AZ, :float
	add_column :autointel_rates, :AR, :float
	add_column :autointel_rates, :CA, :float
	add_column :autointel_rates, :CO, :float
	add_column :autointel_rates, :CT, :float
	add_column :autointel_rates, :DE, :float
	add_column :autointel_rates, :DC, :float
	add_column :autointel_rates, :FL, :float
	add_column :autointel_rates, :GA, :float
	add_column :autointel_rates, :HI, :float
	add_column :autointel_rates, :ID, :float
	add_column :autointel_rates, :IL, :float
	add_column :autointel_rates, :IN, :float
	add_column :autointel_rates, :IA, :float
	add_column :autointel_rates, :KS, :float
	add_column :autointel_rates, :KY, :float
	add_column :autointel_rates, :LA, :float
	add_column :autointel_rates, :ME, :float
	add_column :autointel_rates, :MD, :float
	add_column :autointel_rates, :MA, :float
	add_column :autointel_rates, :MI, :float
	add_column :autointel_rates, :MN, :float
	add_column :autointel_rates, :MS, :float
	add_column :autointel_rates, :MO, :float
	add_column :autointel_rates, :MT, :float
	add_column :autointel_rates, :NE, :float
	add_column :autointel_rates, :NV, :float
	add_column :autointel_rates, :NH, :float
	add_column :autointel_rates, :NJ, :float
	add_column :autointel_rates, :NM, :float
	add_column :autointel_rates, :NY, :float
	add_column :autointel_rates, :NC, :float
	add_column :autointel_rates, :ND, :float
	add_column :autointel_rates, :OH, :float
	add_column :autointel_rates, :OK, :float
	add_column :autointel_rates, :OR, :float
	add_column :autointel_rates, :PA, :float
	add_column :autointel_rates, :PR, :float
	add_column :autointel_rates, :RI, :float
	add_column :autointel_rates, :SC, :float
	add_column :autointel_rates, :SD, :float
	add_column :autointel_rates, :TN, :float
	add_column :autointel_rates, :TX, :float
	add_column :autointel_rates, :UT, :float
	add_column :autointel_rates, :VT, :float
	add_column :autointel_rates, :VA, :float
	add_column :autointel_rates, :WA, :float
	add_column :autointel_rates, :WV, :float
	add_column :autointel_rates, :WI, :float
	add_column :autointel_rates, :WY, :float
 
  end
end
